### ISSUE TITLE
cpu usage placeholder

### ISSUE THREAD

**Issue by GenOpenDiesel** [espidev/ProtectionStones#336]
![image](https://user-images.githubusercontent.com/83091816/178958135-590ddb04-34ad-4102-bbab-86000172e95c.png)
![image](https://user-images.githubusercontent.com/83091816/178958152-1117b13b-0fa0-40d9-98e1-69d084515abc.png)

Hi, I noticed that the placeholder responsible for the number of plots of land uses too much resources - can you do something about it?
all placeholders are updated at the same time.
```
placeholderapi-refresh-intervals:
  default-refresh-interval: 10000
  server:
    '%server_uptime%': 5000

```
