### ISSUE TITLE
Add pt_BR language

### ISSUE THREAD

**Issue by notsapinho** [espidev/ProtectionStones#360]
```yml
cooldown: "&6Atenção: &7Aguarde %time% segundos antes de colocar novamente!"
no_such_command: "&cComando inexistente. Digite /ps ajuda para mais informações"
no_access: "&cVocê não tem permissão para fazer isso aqui."
no_room_in_inventory: "&cVocê não tem espaço suficiente no inventário."
no_room_dropping_on_floor: "&cVocê não tem espaço suficiente no inventário. Soltando o item no chão."
invalid_block: "&cBloco de proteção inválido."
not_enough_money: "&cVocê não tem dinheiro suficiente! O preço é %price%."
paid_money: "&bVocê pagou $%price%."
invalid_world: "&cMundo inválido."
must_be_player: "&cVocê precisa ser um jogador para executar este comando."
go_back_page: Voltar uma página.
go_next_page: Ir para a próxima página.
help: |-
  &8&m=====&r Ajuda do PS &8&m=====
  &b> &7/ps ajuda
help_next: "&7Digite /ps ajuda %page% para ir para a próxima página!"
command_requires_player_name: "&cEste comando requer um nome de jogador."
no_permission_toggle: "&cVocê não tem permissão para usar o comando de alternância."
no_permission_create: "&cVocê não tem permissão para colocar um bloco de proteção."
no_permission_create_specific: "&cVocê não tem permissão para colocar este tipo de bloco de proteção."
no_permission_destroy: "&cVocê não tem permissão para destruir um bloco de proteção."
no_permission_members: "&cVocê não tem permissão para usar comandos de membros."
no_permission_owners: "&cVocê não tem permissão para usar comandos de proprietários."
no_permission_admin: "&cVocê não tem permissão para usar esse comando."
no_permission_count: "&cVocê não tem permissão para usar esse comando."
no_permission_count_others: "&cVocê não tem permissão para usar esse comando."
no_permission_flags: "&cVocê não tem permissão para usar comandos de bandeiras."
no_permission_per_flag: "&cVocê não tem permissão para usar essa bandeira."
no_permission_rent: "&cVocê não tem permissão para alugar."
no_permission_tax: "&cVocê não tem permissão para usar o comando de imposto."
no_permission_buysell: "&cVocê não tem permissão para comprar e vender regiões."
no_permission_unhide: "&cVocê não tem permissão para revelar blocos de proteção ocultos."
no_permission_hide: "&cVocê não tem permissão para ocultar blocos de proteção."
no_permission_info: "&cVocê não tem permissão para usar o comando de informações da região."
no_permission_priority: "&cVocê não tem permissão para usar o comando de prioridade."
no_permission_region: "&cVocê não tem permissão para usar comandos de região."
no_permission_tp: "&cVocê não tem permissão para teleportar para blocos de proteção de outros jogadores."
no_permission_home: "&cVocê não tem permissão para teleportar para seus blocos de proteção."
no_permission_unclaim: "&cVocê não tem permissão para usar o comando de desafirmação."
no_permission_unclaim_remote: "&cVocê não tem permissão para usar o comando de desafirmação remoto."
no_permission_view: "&cVocê não tem permissão para usar o comando de visualização."
no_permission_give: "&cVocê não tem permissão para usar o comando de conceder."
no_permission_get: "&cVocê não tem permissão para usar o comando de obter."
no_permission_sethome: "&cVocê não tem permissão para usar o comando de definir casa."
no_permission_list: "&cVocê não tem permissão para usar o comando de listar."
no_permission_list_others: "&cVocê não tem permissão para usar o comando de listar para outros."
no_permission_name: "&cVocê não tem permissão para usar o comando de nomear."
no_permission_setparent: "&cVocê não tem permissão para usar o comando de definir pai."
no_permission_setparent_others: "&cVocê não tem permissão para herdar de regiões que você não possui."
no_permission_merge: "&cVocê não tem permissão para usar /ps mesclar."
psregion:
  added_to_region: "&b%player%&7 foi adicionado a esta região."
  added_to_region_specific: "&b%player%&7 foi adicionado à região %region%."
  removed_from_region: "&b%player%&7 foi removido da região."
  removed_from_region_specific: "&b%player%&7 foi removido da região %region%."
  not_in_region: "&cVocê não está em uma região de proteção de blocos!"
  player_not_found: "&cJogador não encontrado."
  not_ps_region: "&cNão é uma região de proteção de blocos."
  region_does_not_exist: "&cA região não existe."
  no_regions_owned: "&cVocê não possui nenhuma região protegida neste mundo!"
  no_region_permission: "&cVocê não tem permissão para fazer isso nesta região."
  protected: "&bEsta área agora está protegida."
  no_longer_protected: "&eEsta área não está mais protegida."
  cant_protect_that: "&cVocê não pode proteger essa área."
  reached_region_limit: "&cVocê não pode ter mais regiões protegidas (%limit%)."
  reached_per_block_region_limit: "&cVocê não pode ter mais regiões deste tipo (%limit%)."
  world_denied_create: "&cVocê não pode criar proteções neste mundo."
  region_overlap: "&cVocê não pode colocar um bloco de proteção aqui, pois ele se sobrepõe a outra região."
  region_too_close: "&cSeu bloco de proteção deve estar a um mínimo de %num% blocos da borda de outras regiões!"
  cant_teleport: "&cSeu teletransporte foi bloqueado por uma região de proteção!"
  specify_id_instead_of_alias: |-
    &7Foram encontradas várias regiões com esse nome! Por favor, use um ID em vez disso.
    Regiões com esse nome: &b%regions%
  region_not_adjacent: "&cVocê ultrapassou o limite de regiões não adjacentes! Tente colocar seu bloco de proteção mais próximo de outras regiões que você já possui."
  not_overlapping: "&cEssas regiões não se sobrepõem!"
  multi_region_does_not_exist: Uma dessas regiões não existe!
  no_region_holes: "&cÁrea não protegida detectada dentro da região! Isso não é permitido!"
  delete_region_prevented: "&7A região não pôde ser removida, possivelmente porque isso criaria um buraco na região existente."
  not_owner: "&cVocê não é dono desta região!"
  cannot_merge_rented_region: "&cNão é possível mesclar regiões porque a região %region% está sendo alugada!"
  no_permission_region_type: "&cVocê não tem permissão para ter este tipo de região."
  hidden: "&7O bloco de proteção agora está oculto."
  must_be_placed_in_existing_region: "&cIsso deve ser colocado dentro de uma região existente!"
  already_in_location_is_hidden: "&cJá existe uma região neste local (o bloco de proteção está oculto?)"
  cannot_remove_yourself_last_owner: "&cVocê não pode remover a si mesmo, pois é o último proprietário."
  cannot_remove_yourself_all_regions: "&cVocê não pode remover a si mesmo de todas as suas regiões de uma só vez, por motivos de segurança."
toggle:
  help: "&b> &7/ps toggle|on|off"
  help_desc: Use este comando para ativar ou desativar a colocação de blocos de proteção.
  toggle_on: "&bA colocação de blocos de proteção foi ativada."
  toggle_off: "&bA colocação de blocos de proteção foi desativada."
  count:
  count_help: "&b> &7/ps count [jogador (opcional)]"
  count_help_desc: Contar o número de regiões que você ou outro jogador possui.
  personal_region_count: "&7Seu número de regiões neste mundo: &b%num%"
  personal_region_count_merged: "&7- Incluindo cada região mesclada: &b%num%"
  other_region_count: "&7Número de regiões de %player% neste mundo: &b%num%"
  other_region_count_merged: "&7- Incluindo cada região mesclada: &b%num%"
flag:
  help: "&b> &7/ps flag [nome_da_flag] [valor|null|padrão]"
  help_desc: Use este comando para definir uma flag em sua região protegida.
  flag_set: "A flag %flag% foi definida."
  flag_not_set: "A flag %flag% não foi definida. Verifique seus valores novamente."
  flag_prevent_exploit: "&cIsso foi desativado para evitar explorações."
  flag_prevent_exploit_hover: "&cDesativado por motivos de segurança."
  gui_header: "&8&m=====&r Flags (clique para alterar) &8&m====="
  gui_hover_set: "Clique para definir."
  gui_hover_set_text: |-
    Clique para alterar.
    Valor atual:
    %value%
  hover_change_group: Clique para definir esta flag para aplicar apenas a %group%.
  hover_change_group_null: "&cVocê deve definir este sinalizador com um valor antes de alterar o grupo."
rent:
  help: "&b> &7/ps rent"
  help_desc: Use este comando para gerenciar aluguéis (compra e venda).
  help_header: "&8&m=====&r Ajuda de Aluguel &8&m====="
  already_renting: "&cA região já está sendo alugada! Você deve parar de alugar a região primeiro."
  not_rented: "&cEsta região não está sendo alugada."
  lease_success: |-
    &bTermos de aluguel da região definidos:
    &bPreço: &7%price%
    &bPrazo de Pagamento: &7%period%
  stopped: "&bAluguel encerrado."
  evicted: "&7Despejado o inquilino %tenant%."
  not_renting: "&cEsta região não está sendo alugada para inquilinos."
  paid_landlord: "&b%tenant%&7 pagou &b$%price%&7 para alugar &b%region%&7."
  paid_tenant: "&7Pagou &b$%price%&7 a &b%landlord%&7 pelo aluguel da região &b%region%&7."
  renting_landlord: "&b%player%&7 agora está alugando a região &b%region%&7."
  renting_tenant:
    "&7Agora você está alugando a região &b%region%&7 por &b%price%&7 por
    &b%period%&7."
  not_tenant: "&cVocê não é o inquilino desta região!"
  tenant_stopped_landlord: "&b%player%&7 parou de alugar a região &b%region%&7.
    Agora ela está disponível para outros alugarem."
  tenant_stopped_tenant: "&bVocê parou de alugar a região %region%."
  being_sold: "&cA região está sendo vendida! Faça /ps sell stop primeiro."
  evict_no_money_tenant: "&7Você foi &cdespejado&7 da região &b%region%&7 porque não tem dinheiro suficiente (%price%) para pagar pelo aluguel."
  evict_no_money_landlord:
    "&b%tenant%&7 foi &cdespejado&7 da região &b%region%&7
    porque não têm dinheiro para pagar o aluguel."
  cannot_rent_own_region: "&cVocê não pode alugar sua própria região!"
  reached_limit: "&cVocê atingiu o limite de regiões que pode alugar!"
  price_too_low: "&cO preço do aluguel é muito baixo (deve ser maior do que %price%)."
  price_too_high: "&cO preço do aluguel é muito alto (deve ser menor do que %price%)."
  period_too_short: "&cO período de aluguel é muito curto (deve ser maior do que %period% segundos)."
  period_too_long: "&cO período de aluguel é muito longo (deve ser menor do que %period% segundos)."
  period_invalid: "&cFormato de período inválido! Exemplo: 24h para uma vez por dia."
  cannot_break_while_renting: "&cYou cannot break the region when it is being rented out."
cannot_break_while_renting: "&cVocê não pode quebrar a região enquanto ela estiver sendo alugada."
tax:
  help: "&b> &7/ps tax"
  help_desc: Use este comando para gerenciar e pagar impostos.
  help_header: "&8&m=====&r Ajuda de Impostos &8&m====="
  disabled_region: "&cOs impostos estão desativados para esta região."
  set_as_autopayer:
    "&7Os impostos da região &b%region%&7 serão pagos automaticamente por você."
  set_no_autopayer:
    "&7Os impostos da região &b%region%&7 agora precisam ser pagos manualmente."
  paid: "&7Pagou &b$%amount%&7 em impostos para a região &b%region%&7."
  info_header: "&8&m=====&r Informações de Impostos (clique para mais informações) &8&m====="
  join_msg_pending_payments: |-
    &7Você tem &b$%money%&7 em pagamentos de impostos pendentes em suas regiões!
    Veja-os com /ps tax info.
  player_region_info: "&7> &b%region%&7 - &3$%money% devido"
  player_region_info_autopayer: "&7> &b%region%&7 - &3$%money% devido&7 (você paga automaticamente)"
  click_to_show_more_info: Clique para mostrar mais informações.
  region_info_header: "&8&m=====&r Informações de Impostos da %region% &8&m====="
  region_info: |-
    &9Taxa de Imposto: &7$%taxrate% (soma de todas as regiões mescladas)
    &9Tempo entre ciclos de impostos: &7%taxperiod%
    &9Tempo para pagar impostos após o ciclo: &7%taxpaymentperiod%
    &9Pagador Automático de Impostos: &7%taxautopayer%
    &9Impostos Devidos: &7$%taxowed%
  next_page: "&7Faça /ps tax info -p %page% para ir para a próxima página!"
buy:
  help: "&b> &7/ps buy"
  help_desc: Compre a região em que você está atualmente.
  not_for_sale: "&cEsta região não está à venda."
  stop_sell: "&7A região agora não está mais à venda."
  sold_buyer: "&7Comprou a região &b%region%&7 por &b$%price%&7 de &b%player%&7."
  sold_seller: "&7Vendeu a região &b%region%&7 por &b$%price%&7 para &b%player%&7."
sell:
  help: "&b> &7/ps vender [preço|parar]"
  help_desc: Vende a região em que você está atualmente.
  rented_out: "&cA região está alugada! Você precisa parar de alugar antes de vender."
  for_sale: "&7A região está à venda por &b$%price%&7."
  visibility:
  hide_help: "&b> &7/ps esconder"
  hide_help_desc: Use este comando para esconder ou revelar o bloco de proteção.
  unhide_help: "&b> &7/ps mostrar"
  unhide_help_desc: Use este comando para esconder ou revelar o bloco de proteção.
  already_not_hidden: "&7A pedra de proteção não parece estar escondida..."
  already_hidden: "&7A pedra de proteção parece já estar escondida..."
info:
  help: "&b> &7/ps info membros|proprietários|flags"
  help_desc: Use este comando dentro de uma região ps para ver mais informações sobre ela.
  header: "&8&m=====&r Informações de PS &8&m====="
  type2: "&9Tipo: &7%type%"
  may_be_merged: (pode ser fundido com outros tipos)
  merged2: "&9Regiões mescladas: &7%merged%"
  members2: "&9Membros: &7%members%"
  no_members: "&c(sem membros)"
  owners2: "&9Proprietários: &7%owners%"
  no_owners: "&c(sem proprietários)"
  flags2: "&9Flags: &7%flags%"
  no_flags: (nenhum)
  region2: "&9Região: &b%region%"
  priority2: "&9Prioridade: &b%priority%"
  parent2: "&9Pai: &b%parentregion%"
  bounds_xyz: "&9Limites: &b(%minx%,%miny%,%minz%) -> (%maxx%,%maxy%,%maxz%)"
  bounds_xz: "&9Limites: &b(%minx%, %minz%) -> (%maxx%, %maxz%)"
  seller2: "&9Vendedor: &7%seller%"
  price2: "&9Preço: &7%price%"
  tenant2: "&9Locatário: &7%tenant%"
  landlord2: "&9Proprietário do Aluguel: &7%landlord%"
  rent2: "&9Aluguel: &7%rent%"
  available_for_sale: "&bRegião disponível para venda!"
  available_for_rent: "&bRegião disponível para aluguel!"
priority:
  help: "&b> &7/ps prioridade [número|nulo]"
  help_desc: Use este comando para definir a prioridade da sua região.
  info: "&7Prioridade: %prioridade%"
  set: "&ePrioridade definida."
  error: "&cErro ao analisar a entrada, verifique novamente?"
region:
  help: "&b> &7/ps região [listar|remover|desapropriar] [nome do jogador]"
  help_desc: "Use este comando para encontrar informações ou editar as regiões protegidas de outros jogadores (ou suas
    próprias)."
  not_found_for_player: "&7Nenhuma região encontrada para %player% neste mundo."
  list: "&7Regiões de %player% neste mundo: &b%regiões%"
  remove: "&eRegiões de %player% foram removidas neste mundo, e eles foram removidos das regiões que co-propriedade."
  disown: "&e%player% foi removido como proprietário de todas as regiões neste mundo."
  error_search:
    "&cErro ao procurar as regiões de %player%. Por favor, certifique-se de que
    você digitou o nome correto."
tp:
  help: "&b> &7/ps tp [id/jogador] [número (opcional)]"
  help_desc: Teleporta você para uma das regiões protegidas de um jogador dado.
  number_above_zero: "&cPor favor, digite um número acima de 0."
  valid_number: "&cPor favor, digite um número válido."
  only_has_regions: "&c%player% tem apenas %num% regiões protegidas neste mundo!"
  tping: "&aTeleportando..."
  error_name:
    "&cErro ao teleportar para a região protegida! (erro de análise do nome da região do WG)"
  error_tp: "&cErro ao encontrar a região para teleportar!"
  in_seconds: "&7Teleportando em &b%segundos%&7 segundos."
  cancelled_moved: "&cTeleporte cancelado. Você se moveu!"
home:
  help: "&b> &7/ps home [nome/id]"
  help_desc: Teleporta você para uma de suas regiões protegidas.
  header: "&8&m=====&r Casas (clique para teleportar) &8&m====="
  click_to_tp: Clique para teleportar!
  next_page: "&7Digite /ps home -p %page% para ir para a próxima página!"
  unclaim:
    help: "&b> &7/ps unclaim"
    help_desc: Use este comando para pegar uma pedra de proteção colocada e remover a região.
    header: "&8&m=====&r Desapropriar (clique para desapropriar) &8&m====="
view:
  help: "&b> &7/ps view"
  help_desc: Use este comando para ver as fronteiras de uma região protegida.
  cooldown: "&cPor favor, aguarde um pouco antes de usar /ps view novamente."
  generating: "&7Gerando fronteira..."
  generate_done: "&aFeito! A fronteira desaparecerá após 30 segundos!"
  removing: |-
    &bRemovendo fronteira...
    &aSe você ainda ver blocos fantasmas, faça logout
admin:
  help: "&b> &7/ps admin"
  help_desc: Execute /ps admin help para mais informações.
  cleanup_header: |-
    &eLimpeza %arg% %days% dias
    ================
  cleanup_footer: |-
    &e================
    Limpeza de %arg% concluída.
  hide_toggled: "&eTodos os blocos de proteção foram %message% neste mundo."
  last_logon: "&e%player% jogou pela última vez há %days% dias."
  is_banned: "&e%player% está banido."
  error_parsing: "&cErro ao analisar os dias, tem certeza de que é um número?"
  console_world: "&cPor favor, especifique o mundo como último parâmetro."
  lastlogons_header: |-
    &eMais de %days% dias:
    ================
  lastlogons_line: "&e%player% %time% dias"
  lastlogons_footer: |-
    &e================
    %count% jogadores mostrados no total
    %checked% jogadores verificados no total
reload:
  help: "&b> &7/ps reload"
  help_desc: Recarrega as configurações do arquivo de configuração.
  start: "&bRecarregando configurações..."
  complete: "&bRecarregamento de configurações concluído!"
addremove:
  help: "&b> &7/ps add|remove [nome_do_jogador]"
  help_desc: Use este comando para adicionar ou remover um membro da sua região protegida.
  owner_help: "&b> &7/ps addowner|removeowner [nome_do_jogador]"
  owner_help_desc: Use este comando para adicionar ou remover um proprietário da sua região protegida.
  player_reached_limit: "&cEste jogador atingiu o limite de regiões."
  player_needs_to_be_online: "&cO jogador precisa estar online para adicioná-lo."
get:
  help: "&b> &7/ps get [bloco]"
  help_desc: Use este comando para obter ou comprar um bloco de proteção.
  gotten: "&bBloco de proteção adicionado ao inventário!"
  no_permission_block: "&cVocê não tem permissão para obter este bloco."
  header: "&8&m=====&r Blocos de Proteção (clique para obter) &8&m====="
  gui_block: "&7> &b%alias% &7- %description% (&f$%price%&7)"
  gui_hover: Clique para comprar um %alias%!
give:
  help: "&b> &7/ps give [bloco] [jogador] [quantidade (opcional)]"
  help_desc: Use este comando para dar a um jogador um bloco de proteção.
  given: "&7Deu &b%block%&7 para &b%player%&7."
  no_inventory_room: "&cO jogador não tem espaço suficiente no inventário."
sethome:
  help: "&b> &7/ps sethome"
  help_desc: Use este comando para definir o ponto de início de uma região onde você está no momento.
  set: "&7O ponto de início de &b%psid%&7 foi definido em sua localização."
list:
  help: "&b> &7/ps list [jogador (opcional)]"
  help_desc: Use este comando para listar as regiões que você ou outro jogador possui.
  header: "&8&m=====&r Regiões de %player% &8&m====="
  owner: "&7Proprietário de:"
  member: "&7Membro de:"
  no_regions: "&7Atualmente você não possui nem é membro de nenhuma região."
  no_regions_player: "&b%player% &7não é proprietário nem membro de nenhuma região."
name:
  help: "&b> &7/ps name [nome|nenhum]"
  help_desc:
    Use este comando para dar um apelido à sua região, para facilitar a identificação
    da sua região.
  removed: "&7Removido o nome para %id%."
  set_name: "&7Definido o nome de %id% para &b%name%&7."
  taken: "&7O nome da região &b%name%&7 já foi escolhido! Tente outro nome."
setparent:
  help: "&b> &7/ps setparent [região|nenhum]"
  help_desc:
    Use este comando para permitir que esta região herde propriedades de outra
    região (proprietários, membros, flags, etc.).
  success: "&7Definido com sucesso o pai de &b%id%&7 para &b%parent%&7."
  success_remove: "&7Pai removido com sucesso de &b%id%&7."
  circular_inheritance:
    "&cDetectada herança circular (o pai já herda desta região?). Pai não definido."
merge:
  help: "&b> &7/ps merge"
  help_desc:
    Use este comando para mesclar a região em que você está com outras regiões sobrepostas.
  disabled: A mesclagem de regiões está desativada na configuração!
  merged: "&bRegiões foram mescladas com sucesso!"
  header: "&8&m=====&r Mesclar %region% (clique para mesclar) &8&m====="
  warning: "&7Nota: Isso excluirá todas as configurações da região atual!"
  not_allowed: "&cVocê não tem permissão para mesclar este tipo de região de proteção."
  into: "&bEsta região se sobrepõe a outras regiões com as quais você pode mesclar!"
  no_region: "&7Não há regiões sobrepostas para mesclar."
  click_to_merge: Clique para mesclar com %region%!
  auto_merged: "&7Região mesclada automaticamente com &b%region%&7."
```
